import { createElement } from 'lwc';
import Lightning_uiObjectInfoApi_getPicklistValues from 'c/lightning_uiObjectInfoApi_getPicklistValues';

describe('c-lightning-ui-object-info-api-get-picklist-values', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lightning-ui-object-info-api-get-picklist-values', {
            is: Lightning_uiObjectInfoApi_getPicklistValues
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});